# Generated by Django 3.0.2 on 2020-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrain_fer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitydb',
            name='is_trained',
            field=models.BooleanField(default=False),
        ),
    ]
