# Generated by Django 3.0.3 on 2020-05-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrain_fer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydb',
            name='query',
            field=models.CharField(max_length=800, primary_key=True, serialize=False),
        ),
    ]
