# Generated by Django 3.0.3 on 2020-05-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrain_fer', '0002_auto_20200504_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydb',
            name='query',
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
