# Generated by Django 3.0.3 on 2020-05-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryDB',
            fields=[
                ('query', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='EntityDB',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_name', models.CharField(max_length=64)),
                ('start_pos', models.IntegerField()),
                ('end_pos', models.IntegerField()),
                ('is_trained', models.BooleanField(default=False)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retrain_fer.QueryDB')),
            ],
        ),
        migrations.AddConstraint(
            model_name='entitydb',
            constraint=models.UniqueConstraint(fields=('query', 'start_pos', 'end_pos'), name='unique appversion'),
        ),
    ]
